name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
 
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: run & test Container
      run: docker run -itd --name python-hello -p 8080:8080   my-image-name:latest
    - run: sleep 5 && curl localhost:8080
    - name: change image name 
      run: docker tag my-image-name:latest lidorlg/github-repo:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
   

#  Test:
#    needs: Build
#    runs-on: ubuntu-latest
#    steps:
   # 
#    - name: run & test Container
#      run: docker run -itd --name python-hello -p 8080   my-image-name:latest
